### ISSUE TITLE
Just saying thanks !

### ISSUE THREAD

**Issue by pthom** [jamboree/co2#3]
Just a quick message to say I experimented with your library and really liked it.  Worked perfectly with Visual Studio 2015, clang osx and XCode.
Congrats !

Would you say that it can safely be used in production code (I do not have very high reliability needs, since my target app is gui-driven and does not require 100% availability ) ?

**Comment by jamboree** [comment]
I'm glad you like it :)

> Would you say that it can safely be used in production code

I can only say that if you encounter a bug, I'm always here to help.
What's your use case? Personally, I use it mostly for async programming, and I rarely use the generator stuff.
