### ISSUE TITLE
Support for member functions

### ISSUE THREAD

**Issue by Trigve** [jamboree/co2#7]
I'm trying to use co2 with non-static class member functions but cannot capture the "this" pointer. Is it supported? For now I'm using static member functions with explicit "this" as parameter.

**Comment by jamboree** [comment]
No it's not supported because internally `this` refers to the coroutine frame. The way you're doing is the correct way. Also note that if you're using it for async operation, it's more common to capture this as something like `shared_ptr` to avoid lifetime problem.
